# dev for development, prod for production, comment it out to use default to run with H2 database
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/smartstart?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat: # keep connection alive
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none # create database schema, can be create, create-drop, update, none (must be on production)
  thymeleaf:
    cache: false
server:
  port: 8000

---
spring:
  profiles: prod
  datasource:
    jndi-name: [jndi-name]
